services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MODEL_ID=ekam28/emotion-detector
      - HF_HOME=/app/model_cache
    volumes:
      - ./backend:/app
    networks:
      - mental-health-net
    restart: unless-stopped

networks:
  mental-health-net:
    driver: bridge
